[package]
name = "tiny-multihash-derive"
version = "0.5.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Proc macro for deriving custom multihash tables."
license = "MIT"
repository = "https://github.com/ipfs-rust/tiny-multihash"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.24", features = ["span-locations"] }
proc-macro-crate = "0.1.5"
proc-macro-error = "1.0.4"
quote = "1.0.7"
syn = "1.0.42"
synstructure = "0.12.4"

[features]
default = ["std"]
std = []

[dev-dependencies]
pretty_assertions = "0.6.1"
tiny-multihash = { path = "..", default-features = false }
